#!/bin/sh
echo "prova script configurazione"
java -jar opt/jenkins.war &
echo "sleep 120 sec"
sleep 120s
echo "scarica cli e aggiunge plugin"
curl -O http://localhost:8080/jnlpJars/jenkins-cli.jar
cd jenkins/plugins
curl -O http://updates.jenkins-ci.org/latest/buildresult-trigger.hpi
cd ..
cd ..
